apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deploy.name }}-service
  namespace: {{ .Values.deploy.namespace }}
spec:
  selector:
    app: {{ .Values.deploy.name }}
  ports:
    - name: port
      nodePort: {{ .Values.deploy.nodeport }}
      protocol: TCP
      port: {{ .Values.deploy.port }}
      targetPort: {{ .Values.deploy.port }}
  type: NodePort